channels:
- conda-forge
- defaults
- pytorch

dependencies:
  - python=3.7.12
  - pytorch==1.13.0
  - torchvision==0.14.0
  - jupyter
  - pip
  - pip:
    - scikit-learn==1.0.2
    - pandas==1.3.5
    - numpy==1.21.6
    - timm==0.6.13
    - pytorch-lightning==1.9.5
    - albumentations==1.3.0
    - tqdm
    - imagecodecs
    - pyvips
    - pqdm
    - awscli
    - matplotlib
    - gdown
